-- ============================================================================
-- Chicago Crime Data Warehouse — schema DDL (gold tier)
--
-- Source of truth: docs/dimensional-design.md §8.3 (DDL sketches) and §8.5
-- (reserved "Unknown" rows — seeded by dw_seed.sql, not here).
--
-- This script is invoked by the one-shot DDL bootstrap Lambda (Terraform
-- aws_lambda_invocation) and must be idempotent. Every CREATE uses
-- "IF NOT EXISTS" so re-running on an already-bootstrapped database is a
-- no-op.
--
-- Three schemas per dimensional-design.md §8.2:
--   raw_stg     — typed mirror of silver Parquet (transient, loaded then truncated)
--   dw_staging  — cleansed + joined intermediate (transient)
--   dw          — long-lived star schema, queried by downstream consumers
--
-- V1 scope: only the chicago_crime fact and the dims it needs are loaded.
-- Tables for fact_arrest / dim_arrestee / bridge_arrest_charge are created
-- now so future loaders don't need a schema migration — they are populated
-- when source 5 (Chicago Police Arrests) lands in silver.
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS raw_stg;
CREATE SCHEMA IF NOT EXISTS dw_staging;
CREATE SCHEMA IF NOT EXISTS dw;

-- ----------------------------------------------------------------------------
-- §8.3.1  dim_date — smart-keyed (YYYYMMDD) SCD0 calendar
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dw.dim_date (
    date_key       INTEGER     PRIMARY KEY,
    full_date      DATE        NOT NULL UNIQUE,
    day_of_week    SMALLINT    NOT NULL,
    day_name       TEXT        NOT NULL,
    is_weekend     BOOLEAN     NOT NULL,
    is_us_holiday  BOOLEAN     NOT NULL,
    month_num      SMALLINT    NOT NULL,
    month_name     TEXT        NOT NULL,
    quarter        SMALLINT    NOT NULL,
    year           SMALLINT    NOT NULL,
    iso_week       SMALLINT    NOT NULL
);

-- ----------------------------------------------------------------------------
-- §8.3.2  dim_time_of_day — hourly (0..23) SCD0
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dw.dim_time_of_day (
    time_key       SMALLINT    PRIMARY KEY,
    hour_24        SMALLINT    NOT NULL,
    hour_12        SMALLINT    NOT NULL,
    am_pm          CHAR(2)     NOT NULL,
    period_of_day  TEXT        NOT NULL
);

-- ----------------------------------------------------------------------------
-- §8.3.3  dim_location — SCD2 with embedded Type 1 attributes
--
-- Socioeconomic columns (pct_*, per_capita_income_usd, hardship_index) arrive
-- with source 3 (Community Area Socioeconomics) and are populated lazily.
-- V1 loads only the geographic keys derived from silver chicago_crime.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dw.dim_location (
    location_key            BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_area          SMALLINT,
    district                TEXT,
    ward                    SMALLINT,
    beat                    TEXT,
    block                   TEXT,
    community_area_name     TEXT,
    pct_housing_crowded     NUMERIC(5,2),
    pct_below_poverty       NUMERIC(5,2),
    pct_unemployed_16plus   NUMERIC(5,2),
    pct_no_hs_25plus        NUMERIC(5,2),
    pct_under18_or_over64   NUMERIC(5,2),
    per_capita_income_usd   INTEGER,
    hardship_index          SMALLINT,
    scd_start_date          DATE        NOT NULL,
    scd_end_date            DATE        NOT NULL DEFAULT DATE '9999-12-31',
    is_current              BOOLEAN     NOT NULL DEFAULT TRUE,
    scd_version             SMALLINT    NOT NULL DEFAULT 1,
    scd_hash                BYTEA       NOT NULL,
    UNIQUE (community_area, district, ward, beat, scd_start_date)
);

-- ----------------------------------------------------------------------------
-- §8.3.4  dim_crime_type — SCD2
--
-- index_code ('I' / 'N') and `active` arrive with source 2 (IUCR codes).
-- V1 loads (iucr, primary_type, description, fbi_code) distinct from silver
-- chicago_crime.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dw.dim_crime_type (
    crime_type_key       BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    iucr                 TEXT        NOT NULL,
    primary_type         TEXT,
    description          TEXT,
    fbi_code             TEXT,
    index_code           CHAR(1),
    active               BOOLEAN     NOT NULL DEFAULT TRUE,
    scd_start_date       DATE        NOT NULL,
    scd_end_date         DATE        NOT NULL DEFAULT DATE '9999-12-31',
    is_current           BOOLEAN     NOT NULL DEFAULT TRUE,
    scd_version          SMALLINT    NOT NULL DEFAULT 1,
    scd_hash             BYTEA       NOT NULL,
    UNIQUE (iucr, scd_start_date)
);

-- ----------------------------------------------------------------------------
-- §8.3.5  dim_weather — SCD0 hourly observation
--
-- V1 contains only the reserved -1 "Weather unavailable" row. Populated when
-- source 4 (Open-Meteo) lands in silver.
--
-- IDENTITY is `GENERATED BY DEFAULT` (not ALWAYS) so the seed can supply -1
-- explicitly for the reserved row while letting future weather loads insert
-- without specifying weather_key. New rows start at 1 by default and never
-- collide with -1.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dw.dim_weather (
    weather_key          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    obs_date_key         INTEGER     NOT NULL REFERENCES dw.dim_date (date_key),
    obs_hour             SMALLINT    NOT NULL REFERENCES dw.dim_time_of_day (time_key),
    weather_code_wmo     SMALLINT,
    weather_category     TEXT,
    temp_band            TEXT,
    precip_band          TEXT,
    UNIQUE (obs_date_key, obs_hour)
);

-- ----------------------------------------------------------------------------
-- §8.3.6  dim_crime_flags — junk dim (5 rows, SCD1)
--
-- is_arrest / is_domestic intentionally allow NULL: dimensional-design.md §8.4
-- mandates flags_key=0 = "Unknown" with both booleans NULL. The §8.3.6 sketch
-- declares them NOT NULL which contradicts §8.4; we resolve the doc
-- contradiction in favor of §8.4's reserved-row contract.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dw.dim_crime_flags (
    flags_key       SMALLINT    PRIMARY KEY,
    is_arrest       BOOLEAN,
    is_domestic     BOOLEAN,
    label           TEXT        NOT NULL
);

-- ----------------------------------------------------------------------------
-- §8.3.10  dim_arrestee — SCD1 (created not loaded in V1)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dw.dim_arrestee (
    arrestee_key   BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    race           TEXT,
    age_band       TEXT,
    sex            TEXT
);

-- ----------------------------------------------------------------------------
-- §8.3.7  fact_crime — atomic transaction grain
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dw.fact_crime (
    crime_pk                 BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    crime_id                 BIGINT      NOT NULL UNIQUE,
    case_number              TEXT,
    occurrence_date_key      INTEGER     NOT NULL REFERENCES dw.dim_date (date_key),
    occurrence_time_key      SMALLINT    NOT NULL REFERENCES dw.dim_time_of_day (time_key),
    report_date_key          INTEGER     NOT NULL REFERENCES dw.dim_date (date_key),
    location_key             BIGINT      NOT NULL REFERENCES dw.dim_location (location_key),
    crime_type_key           BIGINT      NOT NULL REFERENCES dw.dim_crime_type (crime_type_key),
    weather_key              BIGINT      NOT NULL REFERENCES dw.dim_weather (weather_key),
    flags_key                SMALLINT    NOT NULL REFERENCES dw.dim_crime_flags (flags_key),
    incident_count           SMALLINT    NOT NULL DEFAULT 1,
    is_arrest                SMALLINT    NOT NULL,
    is_domestic              SMALLINT    NOT NULL,
    hours_to_update          INTEGER,
    latitude                 NUMERIC(9,6),
    longitude                NUMERIC(9,6),
    temperature_celsius      NUMERIC(5,2),
    precipitation_mm         NUMERIC(6,2)
);

CREATE INDEX IF NOT EXISTS ix_fact_crime_date ON dw.fact_crime (occurrence_date_key);
CREATE INDEX IF NOT EXISTS ix_fact_crime_loc  ON dw.fact_crime (location_key);
CREATE INDEX IF NOT EXISTS ix_fact_crime_type ON dw.fact_crime (crime_type_key);

-- ----------------------------------------------------------------------------
-- §8.3.8  fact_arrest — created not loaded in V1
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dw.fact_arrest (
    arrest_pk            BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cb_no                BIGINT      NOT NULL UNIQUE,
    case_number          TEXT,
    arrest_date_key      INTEGER     NOT NULL REFERENCES dw.dim_date (date_key),
    arrest_time_key      SMALLINT    NOT NULL REFERENCES dw.dim_time_of_day (time_key),
    arrestee_key         BIGINT      REFERENCES dw.dim_arrestee (arrestee_key),
    arrest_count         SMALLINT    NOT NULL DEFAULT 1,
    charge_count         SMALLINT    NOT NULL
);

-- ----------------------------------------------------------------------------
-- §8.3.9  bridge_arrest_charge — created not loaded in V1
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dw.bridge_arrest_charge (
    arrest_pk        BIGINT      NOT NULL REFERENCES dw.fact_arrest (arrest_pk),
    crime_type_key   BIGINT      NOT NULL REFERENCES dw.dim_crime_type (crime_type_key),
    charge_position  SMALLINT    NOT NULL,
    charge_class     CHAR(2),
    charge_statute   TEXT,
    PRIMARY KEY (arrest_pk, charge_position)
);
